import { defineConfig } from "oxlint";
import antiSlop from "ultracite/oxlint/anti-slop";
import core from "ultracite/oxlint/core";
import { jsPluginSettings, selectJsPlugins } from "ultracite/oxlint/js-plugins";
import react from "ultracite/oxlint/react";
import tanstackJsPlugins from "ultracite/oxlint/tanstack/js-plugins";
import vitest from "ultracite/oxlint/vitest";

const jsPlugins = selectJsPlugins(["react-doctor"]);

export default defineConfig({
  extends: [core, react, vitest, tanstackJsPlugins, antiSlop, jsPlugins],
  // The preset always sets its list; oxlint's config type leaves the field optional.
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    "src/server/adapters/bindings.ts",
    "src/typeset.css",
    "assets",
  ],
  jsPlugins: jsPlugins.jsPlugins,
  overrides: [
    {
      // Regenerated by `scripts/update-shadcn.sh`, so lint with no autofix is
      // turned off rather than patched into the next regeneration.
      files: ["src/components/ui/**"],
      rules: {
        "anti-slop/require-safety-comment-for-type-assertion": "off",
        "jsx-a11y/click-events-have-key-events": "off",
        "jsx-a11y/label-has-associated-control": "off",
        "jsx-a11y/no-noninteractive-element-interactions": "off",
        "jsx-a11y/prefer-tag-over-role": "off",
        "no-use-before-define": "off",
        "react-doctor/only-export-components": "off",
        "react/jsx-no-constructed-context-values": "off",
        "react/no-object-type-as-default-prop": "off",
        "typescript/no-unsafe-type-assertion": "off",
        "typescript/prefer-nullish-coalescing": "off",
      },
    },
    {
      files: ["**/*.spec.{ts,tsx}"],
      // The preset's own vitest override wins unless this one enables the plugin.
      plugins: ["vitest"],
      rules: {
        // A mock of a promise-returning port has nothing to await; promise-function-async keeps it async.
        "require-await": "off",
        "vitest/consistent-test-filename": [
          "error",
          { pattern: "\\.spec\\.[tj]sx?$" },
        ],
        "vitest/max-expects": "off",
        // tsgolint types a jest-dom matcher under `.resolves` as void, so `expect(await x)` is the form both checkers accept.
        "vitest/prefer-expect-resolves": "off",
      },
    },
  ],
  rules: {
    "func-style": ["error", "declaration", { allowArrowFunctions: true }],
    "react/function-component-definition": [
      "error",
      {
        namedComponents: "function-declaration",
        unnamedComponents: "function-expression",
      },
    ],
    // Reports what the React Compiler cannot compile, and the compiler is not in use.
    "react/todo": "off",
    "unicorn/no-useless-undefined": ["error", { checkArguments: false }],
  },
  settings: jsPluginSettings,
});
