allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
autoInstallPeers: false
color: always
engineStrict: true
minimumReleaseAgeExclude:
  - "@radix-ui/*"
  - happy-dom
  - lucide-react
  - radix-ui
  - "@hookform/*"
  - "@next/*"
  - next
saveExact: true
