allowBuilds:
  esbuild: true
  lefthook: true
  msgpackr-extract: set this to true or false
  sharp: true
  unrs-resolver: true
autoInstallPeers: false
color: always
engineStrict: true
saveExact: true
