
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Read code editor metadata only when the native clipboard still matches the pasted text.
 */
async readCodeClipboard(text: string) : Promise<CodeClipboard | null> {
    return await TAURI_INVOKE("read_code_clipboard", { text });
},
async attachFile(source: string) : Promise<string> {
    return await TAURI_INVOKE("attach_file", { source });
},
async attachImage(base64Data: string) : Promise<string> {
    return await TAURI_INVOKE("attach_image", { base64Data });
},
/**
 * Cancel the quit handshake when a pending write fails.
 */
async cancelQuit() : Promise<void> {
    await TAURI_INVOKE("cancel_quit");
},
async classifyOpenPaths(paths: string[]) : Promise<PendingOpen[]> {
    return await TAURI_INVOKE("classify_open_paths", { paths });
},
async dbSelect(sql: string, params: JsonValue[]) : Promise<JsonValue[][]> {
    return await TAURI_INVOKE("db_select", { sql, params });
},
async deleteNote(path: string) : Promise<null> {
    return await TAURI_INVOKE("delete_note", { path });
},
async findMentions(path: string | null, title: string) : Promise<BareMention[]> {
    return await TAURI_INVOKE("find_mentions", { path, title });
},
async getNotesDir() : Promise<string> {
    return await TAURI_INVOKE("get_notes_dir");
},
async noteExists(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("note_exists", { path });
},
async pendingOpenFiles() : Promise<PendingOpen[]> {
    return await TAURI_INVOKE("pending_open_files");
},
/**
 * Exit after the frontend has flushed its pending writes.
 */
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async readExternal(path: string) : Promise<NoteFile> {
    return await TAURI_INVOKE("read_external", { path });
},
async readNote(path: string) : Promise<NoteFile> {
    return await TAURI_INVOKE("read_note", { path });
},
async reindexAll() : Promise<string[]> {
    return await TAURI_INVOKE("reindex_all");
},
async renameNote(from: string, to: string) : Promise<null> {
    return await TAURI_INVOKE("rename_note", { from, to });
},
async setNotesDir(path: string) : Promise<null> {
    return await TAURI_INVOKE("set_notes_dir", { path });
},
async writeExternal(path: string, content: string) : Promise<MutationReceipt> {
    return await TAURI_INVOKE("write_external", { path, content });
},
async writeNote(path: string, content: string, create: boolean) : Promise<MutationReceipt> {
    return await TAURI_INVOKE("write_note", { path, content, create });
},
/**
 * Open quick capture, or focus its existing window.
 */
async showCapture() : Promise<void> {
    await TAURI_INVOKE("show_capture");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
notesChanged: NotesChanged
}>({
notesChanged: "notes-changed"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * A title written without brackets in another note's prose.
 */
export type BareMention = { context: string; line: number; path: string }
export type CodeClipboard = { language: string | null }
/**
 * A command failure: the kind the caller branches on, and the message it shows.
 */
export type CommandError = { kind: ErrorKind; message: string }
/**
 * Why a command failed. A webview tab has to tell a file that is gone from a
 * read it should retry or report, and a message string cannot carry that.
 */
export type ErrorKind = "failed" | "not-found"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * The file committed by a successful write, with its timestamp in milliseconds.
 */
export type MutationReceipt = { path: string; updatedAt: number }
export type NoteFile = { content: string; updatedAt: number }
/**
 * Relative paths whose saved content or index rows changed; empty means the library.
 */
export type NotesChanged = { paths: string[] }
export type OpenKind = "external" | "note"
/**
 * A queued "Open With" path, classified so the webview opens it as the tab
 * kind the file already is: a note inside the notes dir, external otherwise.
 */
export type PendingOpen = { kind: OpenKind; path: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
