
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Read code editor metadata only when the native clipboard still matches the pasted text.
 */
async readCodeClipboard(text: string) : Promise<CodeClipboard | null> {
    return await TAURI_INVOKE("read_code_clipboard", { text });
},
async attachFile(source: string) : Promise<string> {
    return await TAURI_INVOKE("attach_file", { source });
},
async attachImage(base64Data: string) : Promise<string> {
    return await TAURI_INVOKE("attach_image", { base64Data });
},
/**
 * Cancel the quit handshake when a pending write fails.
 */
async cancelQuit() : Promise<void> {
    await TAURI_INVOKE("cancel_quit");
},
async classifyOpenPaths(paths: string[]) : Promise<PendingOpen[]> {
    return await TAURI_INVOKE("classify_open_paths", { paths });
},
async deleteNote(path: string) : Promise<DeleteReceipt> {
    return await TAURI_INVOKE("delete_note", { path });
},
async findMentions(path: string) : Promise<Mention[]> {
    return await TAURI_INVOKE("find_mentions", { path });
},
async getNotesDir() : Promise<string> {
    return await TAURI_INVOKE("get_notes_dir");
},
async indexStatus() : Promise<IndexStatus> {
    return await TAURI_INVOKE("index_status");
},
async listNotes(filters: NoteFilters) : Promise<NoteMeta[]> {
    return await TAURI_INVOKE("list_notes", { filters });
},
async listTags() : Promise<CountedTag[]> {
    return await TAURI_INVOKE("list_tags");
},
async readGraph(target: GraphTarget) : Promise<GraphResult> {
    return await TAURI_INVOKE("read_graph", { target });
},
async searchNotes(search: NoteSearch) : Promise<NoteMeta[]> {
    return await TAURI_INVOKE("search_notes", { search });
},
async pendingOpenFiles() : Promise<PendingOpen[]> {
    return await TAURI_INVOKE("pending_open_files");
},
/**
 * Exit after the frontend has flushed its pending writes.
 */
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async readExternal(path: string) : Promise<NoteFile> {
    return await TAURI_INVOKE("read_external", { path });
},
async readNote(path: string) : Promise<SavedNote> {
    return await TAURI_INVOKE("read_note", { path });
},
async reindexAll() : Promise<string[]> {
    return await TAURI_INVOKE("reindex_all");
},
async createNote(options: CreateNote) : Promise<MutationReceipt> {
    return await TAURI_INVOKE("create_note", { options });
},
async moveNote(path: string, folder: string) : Promise<PathMutationReceipt> {
    return await TAURI_INVOKE("move_note", { path, folder });
},
async setNotesDir(path: string) : Promise<null> {
    return await TAURI_INVOKE("set_notes_dir", { path });
},
async writeExternal(path: string, content: string, name: SaveName | null) : Promise<MutationReceipt> {
    return await TAURI_INVOKE("write_external", { path, content, name });
},
async saveNote(path: string, content: string, name: SaveName | null) : Promise<MutationReceipt> {
    return await TAURI_INVOKE("save_note", { path, content, name });
},
/**
 * Open quick capture, or focus its existing window.
 */
async showCapture() : Promise<void> {
    await TAURI_INVOKE("show_capture");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
indexStatus: IndexStatus,
mutationWarnings: MutationWarnings,
notesChanged: NotesChanged
}>({
indexStatus: "index-status",
mutationWarnings: "mutation-warnings",
notesChanged: "notes-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type CodeClipboard = { language: string | null }
/**
 * A command failure: the kind the caller branches on, and the message it shows.
 */
export type CommandError = { kind: ErrorKind; message: string }
export type CountedTag = { count: number; tag: string }
export type CreateNote = { content: string | null; folder: string | null; name: NoteName | null }
export type DeleteReceipt = { path: string; warnings: MutationWarning[] }
/**
 * Why a command failed. A webview tab has to tell a file that is gone from a
 * read it should retry or report, and a message string cannot carry that.
 */
export type ErrorKind = "failed" | "not-found"
export type Graph = { dangling: string[]; hubs: HubPill[]; incoming: Mention[]; outgoing: Mention[] }
export type GraphResult = { picture: Picture | null; mentionsError: CommandError | null }
export type GraphTarget = { kind: "note"; path: string } | { kind: "hub"; hub: Hub }
export type Hub = { kind: "folder"; folder: string } | { kind: "tag"; tag: string }
export type HubPill = { count: number; hub: Hub }
/**
 * Whether indexed reads answer now, wait on a scan, or fail until recovery succeeds.
 */
export type IndexStatus = { state: "scanning" } | { state: "ready" } | { state: "failed"; reason: string }
export type Mention = { lines: MentionLine[]; note: NoteMeta }
export type MentionLine = { context: string; line: number; match: string }
export type MutationReceipt = { path: string; updatedAt: number; warnings: MutationWarning[] }
/**
 * A committed file change whose derived index or source cleanup needs attention.
 */
export type MutationWarning = { kind: "index"; path: string; message: string } | { kind: "cleanup"; path: string; message: string }
export type MutationWarnings = { warnings: MutationWarning[] }
export type NoteFile = { content: string; updatedAt: number }
export type NoteFilters = { folder: string | null; limit: number | null; pinnedOnly: boolean | null; query: string | null; sort: NoteSort | null; tag: string | null }
export type NoteMeta = { createdAt: number; folder: string; path: string; pinned: boolean; snippet: string | null; tags: string[]; title: string; updatedAt: number }
export type NoteName = { kind: "filename"; value: string } | { kind: "title"; value: string }
export type NoteSearch = { filters: SearchFilter[]; incomplete: boolean; query: string }
export type NoteSort = "updated"
/**
 * Relative paths whose saved content or index rows changed; empty means the library.
 */
export type NotesChanged = { paths: string[] }
export type OpenKind = "external" | "note"
export type PathMutationReceipt = { path: string; file: NoteFile; remainingSource: string | null; title: string | null; warnings: MutationWarning[] }
/**
 * A queued "Open With" path, classified so the webview opens it as the tab
 * kind the file already is: a note inside the notes dir, external otherwise.
 */
export type PendingOpen = { kind: OpenKind; path: string }
export type Picture = { kind: "note"; note: NoteMeta; graph: Graph } | { kind: "hub"; hub: HubPill; members: RingMember[] }
export type RingMember = { kind: "hub"; pill: HubPill } | { kind: "note"; note: NoteMeta }
export type SaveName = { kind: "heading" } | { kind: "filename"; value: string }
export type SavedNote = { content: string; path: string; pinned: boolean; tags: string[]; title: string; updatedAt: number }
export type SearchFilter = { kind: "folder"; value: string } | { kind: "from"; value: string } | { kind: "link"; value: string } | { kind: "mention"; value: string } | { kind: "tag"; value: string } | { kind: "to"; value: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
