// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Read where the pasted text came from, only while the native clipboard still matches it. */
	readClipboardSource: (text: string) => __TAURI_INVOKE<
/**  A code editor, with the language it named. */
{ kind: "code"; language: string | null } | 
/**
 *  A native rich-text app, such as Terminal, whose plain text flattens its
 *  formatting rather than writing markdown.
 */
{ kind: "richText" } | null>("read_clipboard_source", { text }),
	/**  The clipboard's plain text, if it holds any. */
	readClipboardText: () => __TAURI_INVOKE<string | null>("read_clipboard_text"),
	attachFile: (source: string) => __TAURI_INVOKE<string>("attach_file", { source }),
	attachImage: (base64Data: string) => __TAURI_INVOKE<string>("attach_image", { base64Data }),
	/**  Cancel the quit handshake when a pending write fails. */
	cancelQuit: () => __TAURI_INVOKE<void>("cancel_quit"),
	classifyOpenPaths: (paths: string[]) => __TAURI_INVOKE<PendingOpen[]>("classify_open_paths", { paths }),
	clearConflict: (kind: OpenKind, path: string) => __TAURI_INVOKE<null>("clear_conflict", { kind, path }),
	deleteNote: (path: string) => __TAURI_INVOKE<DeleteReceipt>("delete_note", { path }),
	findMentions: (path: string) => __TAURI_INVOKE<Mention[]>("find_mentions", { path }),
	getNotesDir: () => __TAURI_INVOKE<string>("get_notes_dir"),
	indexStatus: () => __TAURI_INVOKE<IndexStatus>("index_status"),
	listFolders: () => __TAURI_INVOKE<string[]>("list_folders"),
	listNotes: (filters: NoteFilters) => __TAURI_INVOKE<NoteMeta[]>("list_notes", { filters }),
	listTags: () => __TAURI_INVOKE<CountedTag[]>("list_tags"),
	readGraph: (target: GraphTarget) => __TAURI_INVOKE<GraphResult>("read_graph", { target }),
	searchNotes: (search: NoteSearch) => __TAURI_INVOKE<NoteMeta[]>("search_notes", { search }),
	pendingOpenFiles: () => __TAURI_INVOKE<PendingOpen[]>("pending_open_files"),
	/**  Exit after the frontend has flushed its pending writes. */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	readConflict: (kind: OpenKind, path: string) => __TAURI_INVOKE<{
	base: NoteFile,
	ours: string,
} | null>("read_conflict", { kind, path }),
	readExternal: (path: string) => __TAURI_INVOKE<NoteFile>("read_external", { path }),
	readNote: (path: string) => __TAURI_INVOKE<NoteFile>("read_note", { path }),
	reindexAll: () => __TAURI_INVOKE<string[]>("reindex_all"),
	createNote: (options: CreateNote) => __TAURI_INVOKE<MutationReceipt>("create_note", { options }),
	moveNote: (path: string, folder: string) => __TAURI_INVOKE<PathMutationReceipt>("move_note", { path, folder }),
	openExternalFile: (document: string, destination: string) => __TAURI_INVOKE<null>("open_external_file", { document, destination }),
	openLinkedFile: (from: string, destination: string) => __TAURI_INVOKE<null>("open_linked_file", { from, destination }),
	resolveExternalLink: (document: string, destination: string) => __TAURI_INVOKE<PendingOpen>("resolve_external_link", { document, destination }),
	setNotesDir: (path: string) => __TAURI_INVOKE<null>("set_notes_dir", { path }),
	stashConflict: (kind: OpenKind, path: string, stash: ConflictStash) => __TAURI_INVOKE<null>("stash_conflict", { kind, path, stash }),
	writeExternal: (path: string, content: string, name: { kind: "content" } | { kind: "filename"; value: string } | null, expected: string) => __TAURI_INVOKE<SaveOutcome>("write_external", { path, content, name, expected }),
	saveNote: (path: string, content: string, name: { kind: "content" } | { kind: "filename"; value: string } | null, expected: string) => __TAURI_INVOKE<SaveOutcome>("save_note", { path, content, name, expected }),
	/**  Write the webview's current document to `path` as a paginated PDF. */
	exportPdf: (path: string, title: string) => __TAURI_INVOKE<null>("export_pdf", { path, title }),
	/**  Open quick capture, or focus its existing window. */
	showCapture: () => __TAURI_INVOKE<void>("show_capture"),
};

/** Events */
export const events = {
	indexStatus: makeEvent<IndexStatus>("index-status"),
	mutationWarnings: makeEvent<MutationWarnings>("mutation-warnings"),
	notesChanged: makeEvent<NotesChanged>("notes-changed"),
};

/* Types */
/**  Where the pasted text came from, as far as the native clipboard says. */
export type ClipboardSource = 
/**  A code editor, with the language it named. */
{ kind: "code"; language: string | null } | 
/**
 *  A native rich-text app, such as Terminal, whose plain text flattens its
 *  formatting rather than writing markdown.
 */
{ kind: "richText" };

/**  A command failure: the kind the caller branches on, and the message it shows. */
export type CommandError = {
	kind: ErrorKind,
	message: string,
};

/**  Both sides of an unresolved review: the version the edits started from and the edits. */
export type ConflictStash = {
	base: NoteFile,
	ours: string,
};

export type CountedTag = {
	count: number,
	tag: string,
};

export type CreateNote = {
	content: string | null,
	name: NoteName | null,
};

export type DeleteReceipt = {
	path: string,
	warnings: MutationWarning[],
};

/**
 *  Why a command failed. A webview tab has to tell a file that is gone from a
 *  read it should retry or report, and a message string cannot carry that.
 */
export type ErrorKind = "failed" | "not-found";

export type Graph = {
	dangling: string[],
	hubs: HubPill[],
	incoming: Mention[],
	outgoing: Mention[],
};

export type GraphResult = {
	picture: Picture | null,
	mentionsError: CommandError | null,
};

export type GraphTarget = { kind: "note"; path: string } | { kind: "hub"; hub: Hub };

export type Hub = { kind: "folder"; folder: string } | { kind: "tag"; tag: string };

export type HubPill = {
	count: number,
	hub: Hub,
};

export type IndexStatus = { state: "scanning" } | { state: "ready" } | { state: "failed"; reason: string };

export type Mention = {
	lines: MentionLine[],
	note: NoteMeta,
};

export type MentionLine = {
	context: string,
	line: number,
	match: string,
};

export type MutationReceipt = {
	path: string,
	revision: string,
	updatedAt: number,
	warnings: MutationWarning[],
};

/**  A committed file change whose derived index or source cleanup needs attention. */
export type MutationWarning = { kind: "index"; path: string; message: string } | { kind: "cleanup"; path: string; message: string };

export type MutationWarnings = {
	warnings: MutationWarning[],
};

export type NoteFile = {
	content: string,
	revision: string,
	updatedAt: number,
};

export type NoteFilters = {
	folder: string | null,
	includePreview: boolean | null,
	limit: number | null,
	pinnedOnly: boolean | null,
	query: string | null,
	sort: NoteSort | null,
	tag: string | null,
};

/**  One indexed note. In a search result, `title` and `snippet` wrap matched tokens in U+0001 and U+0002, which no markdown file carries. */
export type NoteMeta = {
	createdAt: number,
	folder: string,
	path: string,
	pinned: boolean,
	snippet: string | null,
	tags: string[],
	title: string,
	updatedAt: number,
};

export type NoteName = { kind: "filename"; value: string } | { kind: "title"; value: string };

export type NoteSearch = {
	filters: SearchFilter[],
	incomplete: boolean,
	query: string,
};

export type NoteSort = "updated";

/**  Relative paths whose saved content or index rows changed; empty means the library. */
export type NotesChanged = {
	paths: string[],
};

export type OpenKind = "external" | "note";

export type PathMutationReceipt = {
	path: string,
	file: NoteFile,
	remainingSource: string | null,
	title: string | null,
	warnings: MutationWarning[],
};

/**
 *  A queued "Open With" path, classified so the webview opens it as the tab
 *  kind the file already is: a note inside the notes dir, external otherwise.
 */
export type PendingOpen = {
	kind: OpenKind,
	path: string,
};

export type Picture = { kind: "note"; note: NoteMeta; graph: Graph } | { kind: "hub"; hub: HubPill; members: RingMember[] };

export type RingMember = { kind: "hub"; pill: HubPill } | { kind: "note"; note: NoteMeta };

export type SaveName = { kind: "content" } | { kind: "filename"; value: string };

/**  What a save did: published at the expected revision, or refused because the file moved on. */
export type SaveOutcome = { kind: "committed"; receipt: MutationReceipt } | { kind: "conflict"; file: NoteFile };

export type SearchFilter = { kind: "folder"; value: string } | { kind: "from"; value: string } | { kind: "link"; value: string } | { kind: "mention"; value: string } | { kind: "tag"; value: string } | { kind: "to"; value: string };

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

